### ISSUE TITLE
thumbnails

### ISSUE THREAD

**Issue by demonlibra** [aslze/minirender#1]
It can be very useful program to create thumbnails for stl models if add some options like:
- set background color
- set filename to save image or send image to stdout

**Comment by aslze** [comment]
Hi,

I can add options for background color and output filename to the sample program (which is just a *sample* of how the library can be used). But the file format will be limited to PPM.

This repo is intended as a minimal library with no external dependencies, so no image codecs will be added here. That could be the case for a separate project, though.

**Comment by demonlibra** [comment]
Image format is not a problem. Any who need another image format can use imagemagick.

If it is possible to send data to stdout, convert image to any format is very easy by command:
`render model.stl | convert - model.png`

Save to file not so elegantly but also can be using:
`render model.stl model.ppm`
`convert model.ppm model.png`

**Comment by aslze** [comment]
Hi, latest master version can write to stdout if file name given is "--".

I tried this and it works:

```
render -o -- model.stl | convert - model.png
```

It also tries to fit the model in the view by setting the camera distance (if -d is not given).

The background is still black.

**Comment by demonlibra** [comment]
Checked, working fine.
`./render -o -- -yaw 30 -tilt 40 model.stl | convert - thumb.png`
Thank you.

**Comment by demonlibra** [comment]
Need to change
**A useless software rasterizer for 3D meshes using a z-buffer.**
to
**Fast and compact software rasterizer for 3D meshes using a z-buffer.**

**Comment by aslze** [comment]
:-)

Now you can also set background color:

```
render -bgcolor 10,10,5 ...
```

**Comment by demonlibra** [comment]
Already using **minirender** for my Telegram bot to create thumbnails for STL and STEP files.
Thank you.
