### ISSUE TITLE
Can not convert stl from SolidWorks

### ISSUE THREAD

**Issue by demonlibra** [aslze/minirender#2]
minirender can not convert stl from SolidWorks.
Stl from FreeCAD, VariCAD and PrusaSlicer converting fine.
[base_solidworks.zip](https://github.com/aslze/minirender/files/10673064/base_solidworks.zip)

**Comment by aslze** [comment]
It is a binary STL that begins with the string "solid", so it is being interpreted as an ASCII STL.

https://en.wikipedia.org/wiki/STL_(file_format)#Binary_STL (See how this is discouraged to avoid this problem)

Is "solid base" a name you gave the object? Or is it a name that SolidWorks just adds? Would it work if you rename it (the object, not the file)?

I will try to improve the ASCII vs binary detection somehow...

**Comment by demonlibra** [comment]
It's bad that SolidWorks violates the requirements of the STL format.
I don`t have SolidWorks, but saw many exported stl from different people. All files have 'solid' at the beginning.

At this moment i convert STL from SolidWorks by PrusaSlicer and after create thumbnail by minirender.

**Comment by aslze** [comment]
I just changed the STL loading function. It should work now (master branch).

**Comment by demonlibra** [comment]
Checked. Problem solved.
Thank you.
