### ISSUE TITLE
Stl file with non ASCII letters in name

### ISSUE THREAD

**Issue by demonlibra** [aslze/minirender#3]
If try to convert stl with non ASCII letters in name get empty image.
minirender not send errors to stdout.

```
./render -o image.tiff -tilt 30 -yaw 20 -w 600 -h 600 "€.stl"
load ./render 0.000 s
t = 0.082 (t frame = 0.082)
t paint = 0.014
```
image.tiff is empty.

I can encode file name with non-ASCII letters before use minirender.
Or maybe it is possible to resolve this inside minirender code.

**Comment by aslze** [comment]
Oops. I noticed and fixed an issue that would affect Windows. Then I found an issue that would affect Linux (this one in the ASL library). I think I fixed both, at least temporarily.

Can you pull and check? (the newer ASL should be downloaded automatically)
Are you on Windows or Linux? (I guess Linux)

**Comment by demonlibra** [comment]
Linux.
Checked. Working fine.
